---
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for CSA work sample as part of the interview process.
Parameters:
  InstanceType:
    Description: WebServer EC2 instance.
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instance.
    Type: String
    Default: 0.0.0.0/0
  HTTPLocation:
    Description: The IP address range that will have access to HTTP service on the EC2 instance.
    Type: String
    Default: 0.0.0.0/0
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-west-2:
      HVM64: ami-f2d3638a
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      Comment1: Configure the bootstrap helpers to install the Apache Web Server and PHP
    AWS::CloudFormation::Init:
      config:
        packages:
          yum:
          - httpd
    Properties:
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - EIPAddress=
            - Ref: EIPAddress
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      KeyName:
        Ref: KeyName
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the EC2 instance
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp:
          Ref: HTTPLocation
  EIPAddress:
    Type: AWS::EC2::EIP
  EIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId:
        Ref: EC2Instance
      EIP:
        Ref: EIPAddress
  NewVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 1
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh
Outputs:
  InstanceId:
    Description: InstanceId of this EC2 instance.
    Value:
      Ref: EC2Instance
  InstanceEIPAddress:
    Description: EIP address of this EC2 instance.
    Value:
      Ref: EIPAddress
